name: "Setup"
description: "install docker and qemu, checkout repo"
runs:
  using: composite
  steps:
  - uses: docker/setup-qemu-action@v3
    with:
      platforms: amd64,arm64
  - uses: docker/setup-buildx-action@v13
  - uses: actions/checkout@v4
