name: "Setup"
description: "install docker and qemu"
inputs:
  root:
    description: |
      Project root directory.
      Default '.'
    default: '.'
runs:
  using: composite
  steps:
  - uses: docker/setup-qemu-action@v3
    with:
      platforms: amd64,arm64
  - uses: docker/setup-buildx-action@v3
  
