name: "Setup"
description: "install docker and qemu"
runs:
  using: composite
  steps:
  - uses: docker/setup-qemu-action@v3
    with:
      platforms: amd64,arm64
  - uses: docker/setup-buildx-action@v3
  - shell: bash
    run: |
      echo "date=$(date +'%Y%m%d%H%M')" >> "$GITHUB_ENV"
