FROM ubuntu:latest as builder

COPY . . 
RUN apt-get update &&  apt-get install -y make gcc g++  autoconf libcap-dev
RUN ./autogen.sh && ./configure && make 

FROM ubuntu:latest 
WORKDIR /
RUN apt-get update && \
    apt-get install -y --no-install-recommends libcap-dev && \
    rm -rf /var/lib/apt/lists/*
COPY --from=builder /edge .
COPY --from=builder /supernode .
