FROM alpine:3.15.0

RUN apk -U --no-cache add ca-certificates ceph-common \
    e2fsprogs xfsprogs ebtables ethtool \
    iptables ipset bash kmod socat util-linux  

# Copy the hyperkube binary
COPY ./kubernetes/_output/local/bin/linux/*/kube* /
# COPY ./kubernetes/_output/local/bin/linux/arm64/cloud* /
