FROM alpine:latest

ARG TARGETARCH

RUN apk --no-cache add ca-certificates ceph-common  \
    e2fsprogs xfsprogs ebtables ethtool conntrack-tools \
    iptables ipset bash kmod socat util-linux ; \
    echo 'hosts: files dns' > /etc/nsswitch.conf; \
    rm -rf /sbin/iptables /sbin/iptables-save /sbin/iptables-restore; \
    ln -s /sbin/xtables-nft-multi /sbin/iptables; \
    ln -s /sbin/xtables-nft-multi /sbin/iptables-save; \
    ln -s /sbin/xtables-nft-multi /sbin/iptables-restore


COPY ./_output/local/bin/linux/$TARGETARCH/kube* /
#COPY ./_output/local/bin/linux/$TARGETARCH/cloud* /

