FROM golang:1.16 as builder
WORKDIR /go/src/k8s.io/kubernetes
COPY . .
RUN make kubemark && \
   bash hack/generate-bindata.sh && \
   go test -c ./test/e2e


FROM busybox:latest
WORKDIR /
COPY --from=builder /go/src/k8s.io/kubernetes/e2e.test /e2e.test
COPY --from=builder /go/src/k8s.io/kubernetes/_output/bin/kubemark /kubemark
