FROM golang:1.15 as builder
WORKDIR /go/src/k8s.io/kubernetes
COPY . .
RUN bash hack/generate-bindata.sh && \
   go test -c ./test/e2e

FROM alpine:3.9
WORKDIR /
COPY --from=builder /go/src/k8s.io/kubernetes/e2e.test /e2e.test
