FROM ubuntu:jammy
ARG TARGETPLATFORM
ENV DEBIAN_FRONTEND=noninteractive

# Do not add more stuff to this list that isn't small or critically useful.
# If you occasionally need something on the container do
# sudo apt-get update && apt-get whichever

# hadolint ignore=DL3005,DL3008
RUN apt-get update && \
  apt-get install --no-install-recommends -y \
  ca-certificates \
  curl \
  iptables \
  iproute2 \
  iputils-ping \
  knot-dnsutils \
  netcat \
  tcpdump \
  conntrack \
  bsdmainutils \
  net-tools \
  lsof \
  sudo \
  && update-ca-certificates \
  && apt-get upgrade -y \
  && apt-get clean \
  && rm -rf  /var/log/*log /var/lib/apt/lists/* /var/log/apt/* /var/lib/dpkg/*-old /var/cache/debconf/*-old \
  && update-alternatives --set iptables /usr/sbin/iptables-nft \
  && update-alternatives --set ip6tables /usr/sbin/ip6tables-nft && \
  useradd -m --uid 1337 istio-proxy && \
  echo "istio-proxy ALL=NOPASSWD: ALL" >> /etc/sudoers

COPY $TARGETPLATFORM/pilot-agent /usr/local/bin/pilot-agent
COPY $TARGETPLATFORM/envoy /usr/local/bin/envoy

COPY envoy_bootstrap.json /var/lib/istio/envoy/envoy_bootstrap_tmpl.json

COPY $TARGETPLATFORM/release/stats-filter.wasm /etc/istio/extensions/stats-filter.wasm
COPY $TARGETPLATFORM/release/stats-filter.compiled.wasm /etc/istio/extensions/stats-filter.compiled.wasm
COPY $TARGETPLATFORM/release/metadata-exchange-filter.wasm /etc/istio/extensions/metadata-exchange-filter.wasm
COPY $TARGETPLATFORM/release/metadata-exchange-filter.compiled.wasm /etc/istio/extensions/metadata-exchange-filter.compiled.wasm

# The pilot-agent will bootstrap Envoy.
ENTRYPOINT ["/usr/local/bin/pilot-agent"]
