FROM golang:1.16 as builder

WORKDIR /workspace
COPY . .

# Build
RUN arch="$(uname -m)"; \
    case "$arch" in \
        aarch64) CGO_ENABLED=0 ;; \
        x86_64) CGO_ENABLED=1 ;; \
    esac; \
    CGO_ENABLED=${CGO_ENABLED} go build -o dist/flanneld -ldflags '-s -w -X github.com/flannel-io/flannel/version.Version=v0.14.1 -extldflags "-static"'

FROM alpine:3.15

# iptables use < 1.6.2 when use alpine:3.6

RUN apk add --no-cache iproute2 net-tools ca-certificates iptables strongswan 
COPY --from=builder /workspace/dist/flanneld /opt/bin/flanneld

ENTRYPOINT ["/opt/bin/flanneld"]
