
FROM ubuntu as  builder

WORKDIR /fio

COPY . .

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get -y install gcc mono-mcs libaio-dev libaio1 make && \
    rm -rf /var/lib/apt/lists/* && \
    ./configure && make

FROM ubuntu
RUN apt-get update && \
    apt-get -y install mono-mcs libaio-dev libaio1 vim && \
    rm -rf /var/lib/apt/lists/* 
COPY --from=builder /fio/fio /fio