FROM alpine:3.20

LABEL maintainer "yylt <yang8518296@163.com>"
LABEL source "https://github.com/yylt/build"
LABEL branch "master"
LABEL testtool "curl/nmap/sysbench/iperf/fio/stress-ng"

USER root
# 工具
RUN apk -U --no-cache add curl git nmap sysbench wrk iperf fio stress-ng python3

CMD ["sleep", "10d"]
