# Build the manager binary
FROM golang:1.16.6 as builder

# Copy the Go Modules manifests
COPY . /

# Build
RUN cd /kubernetes  && \
    KUBE_BUILD_PLATFORMS=linux/amd64 make WHAT=cmd/hyperkube

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM yylt/base-hyperkube-image:arm64
WORKDIR /
COPY --from=builder /kubernetes/_output/local/bin/linux/arm64/hyperkube .

ENTRYPOINT ["/hyperkube"]
