
ARG BASE_IMAGE

FROM golang:1.18 as builder
WORKDIR /workspace
COPY . .
RUN export TAG=$(cat TAG) && \
    export REPO_INFO=$(git config --get remote.origin.url)  && \
    export PKG=k8s.io/ingress-nginx  && \
    export ARCH=$(go env GOARCH)  && \
    export COMMIT_SHA=git-$(git rev-parse --short HEAD)  && \
    build/build.sh  && \
    cp rootfs/bin/*/nginx-ingress-controller ./
    

FROM ${BASE_IMAGE}

WORKDIR  /etc/nginx

RUN apk add -U --no-cache \
  diffutils \
  libcap

COPY --from=builder --chown=www-data:www-data /workspace/nginx-ingress-controller /
COPY --from=builder --chown=www-data:www-data /workspace/rootfs /

# Fix permission during the build to avoid issues at runtime
# with volumes (custom templates)
RUN bash -xeu -c ' \
  writeDirs=( \
    /etc/ingress-controller \
    /etc/ingress-controller/ssl \
    /etc/ingress-controller/auth \
    /var/log \
    /var/log/nginx \
  ); \
  for dir in "${writeDirs[@]}"; do \
    mkdir -p ${dir}; \
    chown -R www-data.www-data ${dir}; \
  done'

RUN  setcap    cap_net_bind_service=+ep /nginx-ingress-controller \
  && setcap -v cap_net_bind_service=+ep /nginx-ingress-controller

RUN  setcap    cap_net_bind_service=+ep /usr/local/nginx/sbin/nginx \
  && setcap -v cap_net_bind_service=+ep /usr/local/nginx/sbin/nginx

USER www-data

# Create symlinks to redirect nginx logs to stdout and stderr docker log collector
RUN  ln -sf /dev/stdout /var/log/nginx/access.log \
  && ln -sf /dev/stderr /var/log/nginx/error.log

ENTRYPOINT ["/usr/bin/dumb-init", "--"]

CMD ["/nginx-ingress-controller"]
