FROM rust:latest as builder

WORKDIR /app

COPY source/hello-rs .
RUN apt-get update && \
    apt-get install -y --no-install-recommends protobuf-compiler && \
    rm -rf /var/lib/apt/lists/* && \
    cargo b -r

FROM alpine:3.20

LABEL maintainer "yylt <yang8518296@163.com>"
LABEL source "https://github.com/yylt/build"
LABEL branch "master"
LABEL testtool "curl/nmap/sysbench/iperf/fio/stress-ng"

USER root
# 工具
RUN apk -U --no-cache add curl git nmap sysbench wrk iperf fio stress-ng python3
COPY --from=builder /app/target/release/client /usr/bin
COPY --from=builder /app/target/release/server /usr/bin

CMD ["sleep", "10d"]
