FROM docker.io/yylt/build:202111151020 as builder

WORKDIR /root/go/src/k8s.io/kubernetes/

COPY . .
RUN make kubemark && \
    bash hack/generate-bindata.sh && \
    go test -c ./test/e2e


FROM busybox:latest
WORKDIR /
COPY --from=builder /root/go/src/k8s.io/kubernetes/e2e.test /e2e.test
COPY --from=builder /root/go/src/k8s.io/kubernetes/_output/bin/kubemark /kubemark
