# With this Dockerfile, you can create a container image:
#     $ docker build -f Dockerfile -t bpftool .
# And then use it:
#     $ docker run --rm -ti --privileged --pid=host bpftool prog

# hadolint global ignore=DL3008

FROM ubuntu:22.04 as builder

WORKDIR /
RUN \
	export DEBIAN_FRONTEND=noninteractive && \
	apt-get update && \
	apt-get -y install --no-install-recommends \
		build-essential \
		libelf-dev \
		libz-dev \
        curl \
        git \
		libcap-dev \
		clang llvm llvm-dev lld \
		binutils-dev \
        ca-certificates \
		pkg-config && \
	rm -rf /var/lib/apt/lists/* && \
    llvmf="clang+llvm-16.0.4-aarch64-linux-gnu.tar.xz"; \
    case "$(arch)" in \
        x86_64) llvmf='clang+llvm-16.0.4-x86_64-linux-gnu-ubuntu-22.04.tar.xz' ;; \
    esac; \
	curl -k -o llvm.tar.xz -L "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.4/$llvmf" && \
	tar xf llvm.tar.xz && \
	mv clang+llvm* llvm_build 

COPY . /src
RUN \
    cd /src && \
    git config --global http.sslverify false && \
    git submodule update --init && \
	LLVM_CONFIG=/llvm_build/bin/llvm-config EXTRA_CFLAGS=--static make -C /src/src

FROM ubuntu:22.04
RUN \
	export DEBIAN_FRONTEND=noninteractive && \
	apt-get update && \
	apt-get -y install --no-install-recommends \
		libelf1 \
		llvm && \
	rm -rf /var/lib/apt/lists/*

COPY --from=builder /src/src/bpftool /bin/bpftool

ENTRYPOINT ["/bin/bpftool"]
