ARG BASE_IMAGE=

FROM ${BASE_IMAGE} as BUILD

RUN sed -i 's/  sleep infinity/  sleep 300d/' /entrypoint.sh && \
    chmod +x /entrypoint.sh

FROM debian:12-slim

ARG TARGETPLATFORM

RUN apt-get update && \
    apt-get install -y --no-install-recommends bash && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /usr/src/multus-cni/bin/

COPY --from=BUILD /entrypoint.sh /entrypoint.sh
COPY --from=BUILD /usr/src/multus-cni/bin/multus /usr/src/multus-cni/bin/
COPY --from=BUILD /bandwidth /bandwidth