FROM golang:1.16 as builder
WORKDIR /workspace
COPY . .
RUN CGO_ENABLED=0 GO111MODULE=on go build -o /bin/dnstap ./dnstap


FROM alpine:latest
WORKDIR /
COPY --from=builder /bin/dnstap /usr/local/bin/dnstap

RUN apk add --no-cache bash

ENTRYPOINT ["/usr/local/bin/dnstap"]
