FROM golang:1.23 as builder

WORKDIR /workspace
COPY . .
ARG VERSION=v0.21.5

# Build
RUN arch="$(uname -m)"; \
    case "$arch" in \
        aarch64) CGO_ENABLED=0 ;; \
        x86_64) CGO_ENABLED=1 ;; \
    esac; \
    CGO_ENABLED=${CGO_ENABLED} go build -o dist/flanneld -ldflags '-s -w -X github.com/flannel-io/flannel/version.Version=${VERSION} -extldflags "-static"'

# alpine:3.15(0.8.7 iptable), alpine:3.17(0.8.8 iptables)
FROM alpine:3.15

RUN apk update && \
    apk add --no-cache iproute2 net-tools ca-certificates iptables strongswan ebtables conntrack-tools; \
    echo 'hosts: files dns' > /etc/nsswitch.conf; \
    rm -rf /sbin/iptables /sbin/iptables-save /sbin/iptables-restore; \
    ln -s /sbin/xtables-nft-multi /sbin/iptables; \
    ln -s /sbin/xtables-nft-multi /sbin/iptables-save; \
    ln -s /sbin/xtables-nft-multi /sbin/iptables-restore

COPY --from=builder /workspace/dist/flanneld /opt/bin/flanneld

# not use yet, so skip download
#   apk add wireguard-tools --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community  


ENTRYPOINT ["/opt/bin/flanneld"]