
FROM ubuntu:latest as builder

WORKDIR /workspace

ARG TARGETARCH
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl && \
    case "${TARGETARCH}" in \
        arm64) ARCH='arm64' ;; \
        amd64) ARCH='x86_64' ;; \
    esac; \
    curl -L -k https://github.com/google/go-containerregistry/releases/download/v0.15.2/go-containerregistry_Linux_$ARCH.tar.gz | tar -xzf -  && \
    curl -L -k https://github.com/containerd/containerd/releases/download/v1.7.2/cri-containerd-1.7.2-linux-$TARGETARCH.tar.gz | tar -xzf - && \
    curl -L -k https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_$TARGETARCH -o yq 

FROM annupadhdhyay/helm2:2.12.3 as helm


FROM alpine
RUN  apk -U --no-cache add curl jq git bash openssh netcat-openbsd 
# COPY --from=builder /workspace/usr/local/bin/ctr /usr/bin/
# COPY --from=builder /workspace/usr/local/bin/crictl /usr/bin/
COPY --from=builder /workspace/crane /usr/bin/
COPY --from=builder /workspace/yq /usr/bin/
COPY --from=helm /usr/bin/helm /usr/bin/
