FROM golang:1.19 as builder

COPY . /usr/src

WORKDIR /usr/src
RUN cd sriovdp && \
    make build && \
    cd ../sriovop && \
    make _build-manager BIN_PATH=build/_output/cmd && \
    make _build-sriov-network-config-daemon BIN_PATH=build/_output/cmd && \
    make _build-webhook BIN_PATH=build/_output/cmd

FROM quay.io/centos/centos:stream8
RUN yum -y install hwdata mstflint && yum clean all
COPY --from=builder /usr/src/sriovdp/build/sriovdp /usr/bin/
COPY --from=builder /usr/src/sriovop/build/_output/cmd/manager /usr/bin/
COPY --from=builder /usr/src/sriovop/build/_output/cmd/webhook /usr/bin/
COPY --from=builder /usr/src/sriovop/build/_output/cmd/sriov-network-config-daemon /usr/bin/
COPY --from=builder /usr/src/sriovop/bindata /bindata

