# syntax = docker/dockerfile:1.4
ARG ETCD_IMAGE=gcr.io/etcd-development/etcd:v3.5.26

FROM --platform=$BUILDPLATFORM golang:1.25 AS builder

ARG TARGETOS
ARG TARGETARCH
ARG TARGETPLATFORM

WORKDIR /

COPY . .

ENV GOARCH=${TARGETARCH}

RUN BUILD_PLATFORMS=${TARGETPLATFORM} make build

FROM ${ETCD_IMAGE} as ETCD

FROM debian:12-slim

ARG TARGETPLATFORM

USER root

COPY --from=builder /bin/${TARGETPLATFORM}/etcdcluster /usr/bin/
COPY --from=builder /bin/${TARGETPLATFORM}/ecsnode /usr/bin/

COPY --from=ETCD /usr/local/bin/etcd /usr/bin/
COPY --from=ETCD /usr/local/bin/etcdctl /usr/bin/

RUN apt-get update && \
    apt-get install -y --no-install-recommends dumb-init curl && \
    rm -rf /var/lib/apt/lists/*

USER 65532:65532
ENTRYPOINT ["etcdcluster"]

