---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: secure-container-ecr-deploy
  namespace: {{ .Release.Namespace }}
  labels:
    app: ecr-deploy
    name: secure-container-ecr-deploy
spec:
  selector:
    matchLabels:
      name: secure-container-ecr-deploy
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ecr-deploy
        name: secure-container-ecr-deploy
    spec:
      tolerations:
        - operator: Exists
          effect: NoSchedule
      hostNetwork: true
      hostPID: true
      containers:
        - name: ecr-deploy
          image: {{ tuple .Values.images.tags "ecr_deploy" . | include "helm-toolkit.utils.update_image" }}
          command: ["/entrypoint.sh"]
          resources:
            requests:
              cpu: "100m"
              memory: "10Mi"
            limits:
              cpu: "200m"
              memory: "100Mi"
          securityContext:
            privileged: true
      nodeSelector:
        secure-container: enabled
