apiVersion: node.k8s.io/v1beta1
kind: RuntimeClass
metadata:
  name: rune
handler: ecr
scheduling:
  nodeSelector:
    secure-container: enabled
  tolerations:
    - key: "ecns-compute"
      operator: "Equal"
      value: "enabled"
      effect: "NoSchedule"
