apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      nodeSelector:
        kubernetes.io/hostname: node-1
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 2
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 2 
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: test
---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  ports:
    - port: 80
  selector:
    app: test
---
