FROM docker.io/library/debian:12-slim as builder

ARG http_proxy
ARG https_proxy

ENV http_proxy=$http_proxy
ENV https_proxy=$https_proxy

COPY . /
RUN /build.sh

# Use a multi-stage build
FROM docker.io/library/debian:12-slim

ARG http_proxy
ARG https_proxy

ENV http_proxy=$http_proxy
ENV https_proxy=$https_proxy

ENV PATH=$PATH:/usr/local/luajit/bin:/usr/local/nginx/sbin:/usr/local/nginx/bin

ENV LUA_PATH="/usr/local/share/luajit-2.1.0-beta3/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/lib/lua/?.lua;;"
ENV LUA_CPATH="/usr/local/lib/lua/?/?.so;/usr/local/lib/lua/?.so;;"

COPY --from=builder /usr/local /usr/local

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        bash \
        util-linux \
        libpcre3 \
        libpcre3-dev \
        zlib1g \
        zlib1g-dev \
        libmaxminddb-dev \
        libxslt1-dev \
        libssl-dev \
        ca-certificates \
        libaio-dev \
        libxml2 libxml2-dev \
        coreutils \
  && rm -rf /var/lib/apt/lists/* 

ENV http_proxy=
ENV https_proxy=

