version: '3'
services:
  wechat:
 #   image: docker.yylt.ml/bestwu/wechat
    image: docker.yylt.ml/yylt/weixin:202306190823
    container_name: wechat
    ipc: host
    command:
    - /weixin.sh
    devices:
      - /dev/snd
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/peter/WeChatFiles:/WeChatFiles #使用自己用户目录
    environment:
      - APP=weixin
      - DISPLAY=unix$DISPLAY
      - QT_IM_MODULE=fcitx5
      - XMODIFIERS=@im=fcitx5
      - GTK_IM_MODULE=fcitx5
      - AUDIO_GID=63 # 可选 默认63（fedora） 主机audio gid 解决声音设备访问权限问题
      - GID=1000 # 可选 默认1000 主机当前用户 gid 解决挂载目录访问权限问题
      - UID=1000