name: chatbotui

on:
  push:
    branches: [ chatbotui ]

env:
  REPO: mckaywrigley/chatbot-ui
  PROJECT: ui
  BRANCH: main
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"

    - name: Check out repo code
      uses: actions/checkout@v2

    - name: Check out build code
      uses: actions/checkout@v2
      with:
        repository: ${{ env.REPO }}
        ref: ${{ env.BRANCH }}
        path: ${{ env.PROJECT }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Cache Docker layers
      uses: actions/cache@v2
      id: cache
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx

    - name: Docker Buildx chatbot ui (push)
      run: |
        cd ${{ env.PROJECT }}
        docker buildx build \
          --cache-from "type=local,src=/tmp/.buildx-cache" \
          --platform linux/amd64,linux/arm64 \
          --output "type=image,push=true" \
          --tag yylt/chatbotui:${{ steps.date.outputs.date }} \
          --file ./Dockerfile .

