name: dcgm

permissions:
  contents: read

on:
  push:
    branches: [ dcgm ]

env:
  Dockerfile: Dockerfile-dcgm
  PROJECT: dcgm
  BRANCH: master
  REGISTRY_NAME: ghcr.io

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: |
        echo "name=date::$(date +'%Y%m%d%H%M')" >> "$GITHUB_OUTPUT"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Check out repo code
      uses: actions/checkout@v4

    - name: Check out build code
      uses: actions/checkout@v4
      with:
        repository: easystack/accelerator-manager
        ref: ${{ env.BRANCH }}
        token: ${{ secrets.KPULL }}  
        path: ${{ env.PROJECT }}

    - name: Cache Docker layers
      uses: actions/cache@v2
      id: cache
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY_NAME }}
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.GHCR_PASSWORD }}

    - name: Docker Buildx (push)
      shell: bash
      run: |
        cd ${{ env.PROJECT }}
        commit=$(git rev-parse --short=8 HEAD)
        docker buildx build \
          --cache-from "type=local,src=/tmp/.buildx-cache" \
          --platform linux/arm64,linux/amd64 \
          --output "type=image,push=true" \
          --tag ${{ env.REGISTRY_NAME }}/yylt/dcgm:${commit} \
          --file ../${{ env.Dockerfile }} ./
