name: backend
permissions:
  contents: read

on:
  push:
    branches: [ backend ]

env:
  REGISTRY_NAME: "${{ secrets.MY_HUB_NAME }}"
  REGISTRY_USER: "${{ secrets.MY_HUB_USER }}"
  REGISTRY_PASS: "${{ secrets.MY_HUB_PASSWORD }}"
  Dockerfile: Dockerfile-defaultbackend

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04 
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
    - name: Login to Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY_NAME }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASS }}

    - name: Docker Buildx (push)
      run: |
        docker buildx build \
          --no-cache \
          --platform linux/arm64,linux/amd64 \
          --output "type=image,push=true" \
          --tag ${{ env.REGISTRY_NAME }}/multiarch/defaultbackend:1.5.1 \
          --file ./${{ env.Dockerfile }} ./